import {
  DanielLuImg,
  DanielLuImg2x,
  EmilyLaiImg,
  EmilyLaiImg2x,
  HimaShethImg,
  HimaShethImg2x,
  JuliaDuImg,
  JuliaDuImg2x,
  YashDaniImg,
  YashDaniImg2x,
  JingYiImg,
  JingYiImg2x,
  KarenLeeImg,
  KarenLeeImg2x,
  StephanieDangImg,
  StephanieDangImg2x,
  WinnyYangImg,
  WinnyYangImg2x,
  AngelaWangImg,
  AngelaWangImg2x,
  FaizaanMadhaniImg,
  FaizaanMadhaniImg2x,
  HonyYiChenImg,
  HonyYiChenImg2x,
  OanaBinderImg,
  OanaBinderImg2x,
  RahmaGillanImg,
  RahmaGillanImg2x,
  RiaChakrabortyImg,
  RiaChakrabortyImg2x,
  SarahChunImg,
  SarahChunImg2x,
  SophieQinImg,
  SophieQinImg2x,
  HelenWangImg,
  HelenWangImg2x,
  IsabelLimImg,
  IsabelLimImg2x,
  AlexXieImg,
  AlexXieImg2x,
  StevenXuImg,
  StevenXuImg2x,
  ZafinHassanImg,
  ZafinHassanImg2x,
  SophieLiuImg,
  SophieLiuImg2x,
  JackieChenImg,
  JackieChenImg2x,
  JennyChenImg,
  JennyChenImg2x,
  RahulAggarwalImg,
  RahulAggarwalImg2x,
  KelvinZhangImg,
  KelvinZhangImg2x,
  GraceGaoImg,
  GraceGaoImg2x,
  LeonHanImg,
  LeonHanImg2x,
  RachelXuImg,
  RachelXuImg2x,
  RebeccaFuImg,
  RebeccaFuImg2x,
  SophieWangImg,
  SophieWangImg2x,
  AdvaitMaybhateImg,
  AdvaitMaybhateImg2x,
  AllenLuImg,
  AllenLuImg2x,
  LeonFattakhovImg,
  LeonFattakhovImg2x,
  PatrickZhangImg,
  PatrickZhangImg2x,
  VioletZhouImg,
  VioletZhouImg2x,
  SamuelYangImg,
  EmilyWangImg,
  EmilyWangImg2x,
  EthanGuoImg,
  EthanGuoImg2x,
  JessicaZhangImg,
  JessicaZhangImg2x,
  LaurenYoshidaImg,
  LaurenYoshidaImg2x,
} from "src/assets/img";

export interface Organizer {
  name: string;
  team:
    | "Backend"
    | "Design"
    | "Finance"
    | "Sponsorship"
    | "Frontend"
    | "Co-director"
    | "Internal Operations"
    | "Sponsorship Advisor"
    | "Logistics Advisor"
    | "Logistics"
    | "Marketing"
    | "Product Manager";
  emoji: string;
  img: string;
  isSquare: boolean;
  backgroundNum: number;
  srcSet?: string;
}

const getBackgroundNum = () => Math.round(Math.random() * 4);

export const ORGANIZERS: Organizer[] = [
  {
    name: "Daniel Lu",
    team: "Sponsorship",
    emoji: "🚀",
    img: DanielLuImg,
    isSquare: false,
    srcSet: `${DanielLuImg} 1x, ${DanielLuImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Emily Lai",
    team: "Sponsorship",
    emoji: "🦋",
    img: EmilyLaiImg,
    isSquare: false,
    srcSet: `${EmilyLaiImg} 1x, ${EmilyLaiImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Hima Sheth",
    team: "Sponsorship",
    emoji: "😤",
    img: HimaShethImg,
    isSquare: false,
    srcSet: `${HimaShethImg} 1x, ${HimaShethImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Yash Dani",
    team: "Sponsorship",
    emoji: "🤩",
    img: YashDaniImg,
    isSquare: false,
    srcSet: `${YashDaniImg} 1x, ${YashDaniImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Julia Du",
    team: "Sponsorship",
    emoji: "😌",
    img: JuliaDuImg,
    isSquare: false,
    srcSet: `${JuliaDuImg} 1x, ${JuliaDuImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Jing Yi Wang",
    team: "Sponsorship",
    emoji: "✨",
    img: JingYiImg,
    isSquare: false,
    srcSet: `${JingYiImg} 1x, ${JingYiImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Karen Lee",
    team: "Marketing",
    emoji: "🌼",
    img: KarenLeeImg,
    isSquare: false,
    srcSet: `${KarenLeeImg} 1x, ${KarenLeeImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Stephanie Dang",
    team: "Marketing",
    emoji: "🤗",
    img: StephanieDangImg,
    isSquare: false,
    srcSet: `${StephanieDangImg} 1x, ${StephanieDangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Winny Yang",
    team: "Marketing",
    emoji: "🤡",
    img: WinnyYangImg,
    isSquare: false,
    srcSet: `${WinnyYangImg} 1x, ${WinnyYangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Angela Wang",
    team: "Logistics",
    emoji: "🤯",
    img: AngelaWangImg,
    isSquare: false,
    srcSet: `${AngelaWangImg} 1x, ${AngelaWangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Rahma Gillan",
    team: "Logistics",
    emoji: "🥴",
    img: RahmaGillanImg,
    isSquare: false,
    srcSet: `${RahmaGillanImg} 1x, ${RahmaGillanImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Faizaan Madhani",
    team: "Logistics",
    emoji: "😶",
    img: FaizaanMadhaniImg,
    isSquare: false,
    srcSet: `${FaizaanMadhaniImg} 1x, ${FaizaanMadhaniImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Hong Yi Chen",
    team: "Logistics",
    emoji: "😢",
    img: HonyYiChenImg,
    isSquare: false,
    srcSet: `${HonyYiChenImg} 1x, ${HonyYiChenImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Oana Binder",
    team: "Logistics",
    emoji: "😎",
    img: OanaBinderImg,
    isSquare: false,
    srcSet: `${OanaBinderImg} 1x, ${OanaBinderImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Ria Chakraborty",
    team: "Logistics",
    emoji: "😜",
    img: RiaChakrabortyImg,
    isSquare: false,
    srcSet: `${RiaChakrabortyImg} 1x, ${RiaChakrabortyImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Sarah Chun",
    team: "Logistics",
    emoji: "😇",
    img: SarahChunImg,
    isSquare: false,
    srcSet: `${SarahChunImg} 1x, ${SarahChunImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Sophie Qin",
    team: "Logistics",
    emoji: "👀",
    img: SophieQinImg,
    isSquare: false,
    srcSet: `${SophieQinImg} 1x, ${SophieQinImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Helen Wang",
    team: "Finance",
    emoji: "🤗",
    img: HelenWangImg,
    isSquare: false,
    srcSet: `${HelenWangImg} 1x, ${HelenWangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Isabel Lim",
    team: "Finance",
    emoji: "🍟",
    img: IsabelLimImg,
    isSquare: false,
    srcSet: `${IsabelLimImg} 1x, ${IsabelLimImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Alex Xie",
    team: "Frontend",
    emoji: "🌻",
    img: AlexXieImg,
    isSquare: false,
    srcSet: `${AlexXieImg} 1x, ${AlexXieImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Steven Xu",
    team: "Frontend",
    emoji: "😩",
    img: StevenXuImg,
    isSquare: false,
    srcSet: `${StevenXuImg} 1x, ${StevenXuImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Jackie Chen",
    team: "Frontend",
    emoji: "🤨",
    img: JackieChenImg,
    isSquare: false,
    srcSet: `${JackieChenImg} 1x, ${JackieChenImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Jenny Chen",
    team: "Frontend",
    emoji: "🌝",
    img: JennyChenImg,
    isSquare: false,
    srcSet: `${JennyChenImg} 1x, ${JennyChenImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Kelvin Zhang",
    team: "Frontend",
    emoji: "😁",
    img: KelvinZhangImg,
    srcSet: `${KelvinZhangImg} 1x, ${KelvinZhangImg2x} 2x`,
    isSquare: false,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Rahul Aggarwal",
    team: "Frontend",
    emoji: "🤔",
    img: RahulAggarwalImg,
    srcSet: `${RahulAggarwalImg} 1x, ${RahulAggarwalImg2x} 2x`,
    isSquare: false,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Sophie Liu",
    team: "Frontend",
    emoji: "🌸",
    img: SophieLiuImg,
    isSquare: false,
    srcSet: `${SophieLiuImg} 1x, ${SophieLiuImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Zafin Hassan",
    team: "Frontend",
    emoji: "🇧🇩",
    img: ZafinHassanImg,
    isSquare: false,
    srcSet: `${ZafinHassanImg} 1x, ${ZafinHassanImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Grace Gao",
    team: "Design",
    emoji: "👍",
    img: GraceGaoImg,
    isSquare: false,
    srcSet: `${GraceGaoImg} 1x, ${GraceGaoImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Leon Han",
    team: "Design",
    emoji: "🤦",
    img: LeonHanImg,
    isSquare: false,
    srcSet: `${LeonHanImg} 1x, ${LeonHanImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Rachel Xu",
    team: "Design",
    emoji: "🤩",
    img: RachelXuImg,
    isSquare: false,
    srcSet: `${RachelXuImg} 1x, ${RachelXuImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Rebecca Fu",
    team: "Design",
    emoji: "🤠",
    img: RebeccaFuImg,
    srcSet: `${RebeccaFuImg} 1x, ${RebeccaFuImg2x} 2x`,
    isSquare: false,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Sophie Wang",
    team: "Design",
    emoji: "🥳",
    img: SophieWangImg,
    isSquare: false,
    srcSet: `${SophieWangImg} 1x, ${SophieWangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Advait Maybhate",
    team: "Backend",
    emoji: "🤯",
    img: AdvaitMaybhateImg,
    isSquare: false,
    srcSet: `${AdvaitMaybhateImg} 1x, ${AdvaitMaybhateImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Allen Lu",
    team: "Backend",
    emoji: "🤠",
    img: AllenLuImg,
    isSquare: false,
    srcSet: `${AllenLuImg} 1x, ${AllenLuImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Leon Fattakhov",
    team: "Backend",
    emoji: "🎆",
    img: LeonFattakhovImg,
    isSquare: false,
    srcSet: `${LeonFattakhovImg} 1x, ${LeonFattakhovImg} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Patrick Zhang",
    team: "Backend",
    emoji: "💩",
    img: PatrickZhangImg,
    isSquare: false,
    srcSet: `${PatrickZhangImg} 1x, ${PatrickZhangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Violet Zhou",
    team: "Backend",
    emoji: "👻",
    img: VioletZhouImg,
    isSquare: false,
    srcSet: `${VioletZhouImg} 1x, ${VioletZhouImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Samuel Yang",
    team: "Backend",
    emoji: "🌵",
    img: SamuelYangImg,
    isSquare: false,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Emily Wang",
    team: "Co-director",
    emoji: "🌊",
    img: EmilyWangImg,
    isSquare: false,
    srcSet: `${EmilyWangImg} 1x, ${EmilyWangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Ethan Guo",
    team: "Product Manager",
    emoji: "🙃",
    img: EthanGuoImg,
    isSquare: false,
    srcSet: `${EthanGuoImg} 1x, ${EthanGuoImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Jessica Zhang",
    team: "Co-director",
    emoji: "✌️",
    img: JessicaZhangImg,
    isSquare: false,
    srcSet: `${JessicaZhangImg} 1x, ${JessicaZhangImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
  {
    name: "Lauren Yoshida",
    team: "Internal Operations",
    emoji: "✌️",
    img: LaurenYoshidaImg,
    isSquare: false,
    srcSet: `${LaurenYoshidaImg} 1x, ${LaurenYoshidaImg2x} 2x`,
    backgroundNum: getBackgroundNum(),
  },
];
